const propiedadesAlquiler = [
  {
    nombre: "Apartamento Moderno en el Centro",
    src: "/assets/img/departamento_arriendo1.png",
    descripcion: "Un moderno apartamento con diseño minimalista",
    ubicacion: "Centro Urbano, 5th Avenue",
    habitaciones: 1,
    costo: 289000,
    smoke: false,
    pets: false,
  },
  {
    nombre: "Vivienda Conveniente en El Valle",
    src: "/assets/img/departamento_arriendo2.png",
    descripcion: "Espacioso y bien mantenido, ideal para estudiantes",
    ubicacion: "El Valle, Avenida del Sol",
    habitaciones: 2,
    costo: 350000,
    smoke: true,
    pets: true,
  },
  {
    nombre: "Casa de Campo con Piscina",
    src: "/assets/img/departamento_arriendo3.png",
    descripcion: "Casa en el paisaje, con jardín y piscina privada",
    ubicacion: "Zona Rural, Ruta de los Puentes",
    habitaciones: 3,
    costo: 520000,
    smoke: false,
    pets: true,
  },
  {
    nombre: "Minisplit en el Paseo de la Plaza",
    src: "/assets/img/departamento_arriendo4.png",
    descripcion:
      "Pequeño departamento de una sola planta, muy cercano al centro",
    ubicacion: "Paseo de la Plaza, 1001",
    habitaciones: 1,
    costo: 190000,
    smoke: false,
    pets: false,
  },
  {
    nombre: "Oficina de Alto Rendimiento en el Edificio Central",
    src: "/assets/img/departamento_arriendo5.png",
    descripcion: "Espacio profesional con conexión WiFi y aire acondicionado",
    ubicacion: "Edificio Central, 3er Piso",
    habitaciones: 1,
    costo: 310000,
    smoke: true,
    pets: false,
  },
];
